//AUTH
export const RESTORE_TOKEN = 'RESTORE_TOKEN'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const LOADING = 'LOADING'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const RESTORE_TOKEN_FAIL = 'RESTORE_TOKEN_FAIL'

//NOTICES
export const GET_NOTICES_SUCCESS = 'GET_NOTICES_SUCCESS'
export const GET_NOTICES_FAIL = 'GET_NOTICES_FAIL'
export const ADD_NOTICE_SUCCESS = 'ADD_NOTICE_SUCCESS'
export const ADD_NOTICE_FAIL = 'ADD_NOTICE_FAIL'
export const ADD_COMMENT_NOTICE_SUCCESS = 'ADD_COMMENT_NOTICE_SUCCESS'
export const ADD_COMMENT_NOTICE_FAIL = 'ADD_COMMENT_NOTICE_FAIL'
export const DELETE_NOTICE_SUCCESS = 'DELETE_NOTICE_SUCCESS'
export const DELETE_NOTICE_FAIL = 'DELETE_NOTICE_FAIL'