export const RESTORE_TOKEN = 'RESTORE_TOKEN'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const LOADING = 'LOADING'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const RESTORE_TOKEN_FAIL = 'RESTORE_TOKEN_FAIL'